### ISSUE TITLE
menu/page_size 不生效

### ISSUE THREAD

**Issue by YUX** [maomiui/rime#22]
无论是几都是只有5个候选词

**Comment by maomiui** [comment]
已修复。
方法：打开`luna_pinyin_simp.custom.yaml` 下拉至底部找到动态时间代码，
将代码 ~~`"engine/translators/+": lua_translator@date_translator`~~
修改为`"engine/translators/@6": lua_translator@date_translator`

**Comment by YUX** [comment]
感谢

**Comment by DivineRapierH** [comment]
我遇到了同样的问题，使用的版本已经是`"engine/translators/@6": lua_translator@date_translator`了，但在`default.custom.yaml`中修改`menu/page_size`始终不生效，后来在检查`build`路径下生成的`luna_pinyin.schema.yaml`中发现了：
```yaml
menu:
  page_size: 5
```
于是在`luna_pinyin.custom.yaml`中添加`menu/page_size`自定义项，这才终于生效了。
我初次接触 RIME，不是特别了解原理，初步猜测是`luna_pinyin.schema.yaml`中的`menu/page_size`选项覆盖了`default.yaml`中的对应项，但感觉这种覆盖有点违背正常逻辑。
