### ISSUE TITLE
关于“特定程序里中文输入英文标点”的应用程序名获取

### ISSUE THREAD

**Issue by loong1992** [maomiui/rime#25]
应用程序名获取：打开“活动监视器”，选中对应程序名称，然后点击“查看所选进程信息”的按钮，再点击“取样”，出来的“Identifier”栏就是应用名。

建议这个语句修改通顺后加到readme.md说明里面，不是人人都是开发者知道程序完整的名称。

**Comment by maomiui** [comment]
感谢，已加入说明。
