### ISSUE TITLE
开启模糊音后，Emoji 、动态时间失效。

### ISSUE THREAD

**Issue by xiyizhou** [maomiui/rime#27]
在 `luna_pinyin_simp.custom.yaml` 中开启
`- derive/^([zcs])h/$1/             # zh, ch, sh => z, c, s`
`- derive/^([zcs])([^h])/$1h$2/     # z, c, s => zh, ch, sh`
模糊音后，Emoji ，动态时间失效

**Comment by maomiui** [comment]
可能是和开启模糊音无法使用超级简拼冲突，已修复，重新下载 `luna_pinyin_simp.custom.yaml` 覆盖，重新部署试试。

**Comment by xiyizhou** [comment]
> 可能是和开启模糊音无法使用超级简拼冲突，已修复，重新下载 `luna_pinyin_simp.custom.yaml` 覆盖，重新部署试试。

新文件 还是不行

**Comment by maomiui** [comment]
测试正常
![](https://i.loli.net/2021/05/13/CmpzEvWA1PoIqZy.png)
![](https://i.loli.net/2021/05/13/w7k6KCL8DjiQVyu.png)

**Comment by xiyizhou** [comment]
神奇了，可能与我的其他设置有关。
![iShot2021-05-14 09 13 27](https://user-images.githubusercontent.com/55862635/118206280-bdf45d00-b494-11eb-8b01-5757143a0817.png)
![iShot2021-05-14 09 13 07](https://user-images.githubusercontent.com/55862635/118206286-c056b700-b494-11eb-8b40-cb7c9be8c923.png)
![iShot2021-05-14 09 11 03](https://user-images.githubusercontent.com/55862635/118206290-c351a780-b494-11eb-908d-06100cc6e2e4.png)
![iShot2021-05-14 09 10 53](https://user-images.githubusercontent.com/55862635/118206296-c5b40180-b494-11eb-916c-3cb2bf8bb670.png)

**Comment by maomiui** [comment]
使用 Visual Studio Code 软件打开`.yaml`文件，怎么看你使用文本编辑打开？

**Comment by xiyizhou** [comment]
> 使用 Visual Studio Code 软件打开`.yaml`文件，怎么看你使用文本编辑打开？

用 VS 问题解决，谢谢！
