### ISSUE TITLE
macOS下无法用 [] 实现翻页及候选词个数显示不全

### ISSUE THREAD

**Issue by LeiGitWing** [maomiui/rime#31]
## 0. 环境
系统：macOS BigSur 11.4

## 1. 已尝试的解决方案：
- [x] issues 内搜索
- [x] 重启电脑及鼠须管

均未果

## 2. 问题描述
第一个问题。图片如下

![G2zKjXT8FW75UZV](https://i.loli.net/2021/07/29/G2zKjXT8FW75UZV.png)

配置文件中使用减号和等号能正常翻页，按下 ] 后却无法翻页。以下是 default.custom.yaml 中的代码片段。

```
key_binder/bindings: # 翻页(若要开启,去掉前面的#号)
    - { when: paging, accept: bracketleft, send: Page_Up }      # "["上一页
    - { when: has_menu, accept: bracketright, send: Page_Down } # "]"下一页
```

第二个问题。修改了 `default.custom.yaml` 中的 `menu/page_size: 7`，点击鼠须管中的 `Deploy`。等待后候选词依然只有 5 个。又尝试修改成其他数值，均无变化。

**Comment by maomiui** [comment]
1. 首次翻页是按 `]`，你提到的 `[` 是向上翻页。
2. 候选词个数经测试正常，如果你的配置文件是很早之前的参考 #22 。如果仍不行建议重新下载配置文件重新部署（个人词库先备份）。

**Comment by LeiGitWing** [comment]
重新安装配置文件后能翻页和修改备选词了，nice
