### ISSUE TITLE
词库里的字符串，打字不出现

### ISSUE THREAD

**Issue by BH1SCW** [maomiui/rime#35]
比如我对照字库里的来输入：

![](https://i.imgur.com/iNXDCgP.png)

想请教一下这是什么原因？ 还是说原本就这样的
个人直觉是优先词库里匹配
还有个疑问如果加载多个词库，有重复的词条这个优先级怎么来显示？

**Comment by maomiui** [comment]
1. `luna_pinyin.sogou.dict.yaml` 已包含绝大部份词库，包括你说的 `不烫头`。
2. 外挂词库方法查看目录 [11](https://github.com/maomiui/rime#%E8%AF%8D%E5%BA%93%E6%96%87%E6%A1%A3%E6%A0%BC%E5%BC%8F) 和[12](https://github.com/maomiui/rime#%E5%A4%96%E6%8C%82%E8%AF%8D%E5%BA%93)。

**Comment by BH1SCW** [comment]
多谢回复， 1， 我的意思是：按理说不烫头在sogou词库了，而且我看到也加载了扩展词库， 但是打字却没有提示“不烫头” 而是 “不汤头”， 类似的例子我试了几个，很多这样的case

2， 外挂词库我已经搞定了，把之前搜狗的个人词库转换过来加载上了

顺便再提一个小问题， 我发现小鹤双拼貌似是用替换的方法把按键转换成全拼，然后用全拼来匹配词库，
这样有个问题是比如四字成语之前是可以选每个字第一个字母来打，现在却需要把全部按一遍才行，请问这个有解吗？

**Comment by maomiui** [comment]
不提示某些词库，说明没有载入成功，建议使用 Visual Studio Code 软件打开配置文件。
双拼没设置词库，需要个人自己设置。
